# An epidemiological overview of Covid-19

The emergence of Covid-19 had policy-makers searching for accurate information about the current state of affairs and likely developments in the future. But tracking a pandemic is not easy and it is also not immediately clear what aspects to look at. Should we track the number of reported cases, should we look at deaths or should we analsyse $R_t$, the average number of people each person infected at time $t$ will infect in the future? 

This chapter is going to give an overview of the information these quantities provide and discuss issues surrounding their estimation. These epidemiological aspects are not strictly relevant for the discussion of forecast evaluation and ensembling in chapter X and Y, but they were an important part of my work at LSHTM and form an important background for understanding the model choices in chapter XXX


## Overview of epidemiological prediction targets

Many different quantities may be of interest depending on the specific decisions to be made. These include e.g. current and future incidences or cumulative numbers of cases and deaths, the number of people who need a ventilator or treatment in an intensive care unit (ICU), or indicators about the likely trajectory of the epidemic. 

Metrics that directly capture the trajectory of the epidemic include the effective reproduction number and the doubling or halving time. The effective reproduction number, $R_t$ is the expected number of people that each infected person at time $t$ will infect themselves. In contrast to the basic reproduction number, $R_0$, the effective reproduction number varies over time, e.g. with changes in behaviour or different interventions implemented. The doubling or halving time is the time expected until the number of cases doubles or halves, depending on the state of the epidemic. These quantities can be a useful basis for policy decision, e.g. about lockdowns, but they are hard to estimate. Also, there exists no ground truth against which different models could be compared. 

The obvious prediction target is the number of infected cases. 



## Estimating cases

issues: 
- reporting delays
- weekday effect
- testing / underreporting

In theory it seems straightforward: just look at the number of infected cases and see how they develop over time. There are, however, quite a lot of complicating factors. 

First, it is not immediately clear what a case is. Should we count only the people who have a confirmed PCR test? Should we also count those who are clinically confirmed cases, i.e. whose who very clearly present all the symptoms associated with Covid-19? What about probable cases, who could also have a different pneumonia? This was mostly an issue at a time when PCR tests were not readily available. E.g.: the large China spike in cases. -- do inconsistent case definitions still pose a problem? --

Secondly, it is not clear, when a case appeared. Cases are not reported immediately, but are subject to different delays and weekday effects. Patients may not be able to see a docotr over the weekend or hospitals do not forward cases to the authorities until the next Monday. The easiest, of course, is to just stick with the day of report. For many practical purposes, however, we need to figure out the date of symptom onset or even the date of infection of a patient. Some countries publish very detailed linelists. These documents contain information about the estimated date of onset or date of infection of a particular person. Oftentimes, however epidemiologists can do very little except estimate delay distributions

Case definitions: 
- reported cases
- onset cases
- cases on the date of infection


## Estimating deaths
pro: 
- less fluctuation
- you get almost all cases that die

con: 
- long delay
- dying from / with covid --> what is a death? 


## Transferring between different quantities
from reported cases onset cases to infections to deaths 

## Estimating $R$
One simple metric to track the trajectory of an epidemic is the so called $R$ value. $R$ is the expected number of people that each infected person will infect themselves. If $R$ is consistently below one, then the number of cases will eventually decrease. If it is above one, the epidemic grows exponentially. If the $R$ value is tracked over time we denote it $R_t$. 

Plot? 

### Estimating $R_t$ 

distortions: different parts of the epidemic, changes in reporting


### Doubling and halving times

### Estimating $R_t$ from cases





